src/models/api/dot/routes.py
from flask_restplus import Resource, Namespace, fields
from flask import jsonify, g
from flask import request

from flask_httpauth import HTTPTokenAuth
import src.models.api.guser as guser
from src.models.api.dot.Admin import AdminAPI

admin_namespace = Namespace('DOT Admin', 'There are Various Operations regarding Admin')

auth = HTTPTokenAuth(scheme='Token')


@auth.verify_token
def verify_token(token):
    if token in guser.tokens:
        g.current_user = guser.tokens[token]

        return True
    return False


admin_model = admin_namespace.model('Admin', {
    'username': fields.String(required=True, description='Admin Username'),
    'password': fields.String(required=True, description='Admin Password'),
    'name': fields.String(required=True, description='Admin Name'),
    'privileges': fields.String(required=True, description='Admin Privileges')
})


@admin_namespace.route('/')
class ListUser(Resource):
    def get(self):
        users = AdminAPI.get_all_admin()
        return jsonify({"data": users})

    @admin_namespace.doc(params={
        'username': {'in': 'formData', 'description': 'Admin Username', 'required': 'True'},
        'password': {'in': 'formData', 'description': 'Admin Password', 'required': 'True'},
        'name': {'in': 'formData', 'description': 'Admin Name', 'required': 'True'},

        'privileges': {'in': 'formData', 'description': 'User Privileges', 'required': 'True'}
    })
    def post(self):
        username = request.form['username']
        name = request.form['name']
        password = request.form['password']
        privileges = request.form['privileges']
        if AdminAPI.create_new_user(username=username, name=name, password=password, privileges=privileges):
            return {'msg': 'Admin created Successfully'}, 201
        else:
            return {'msg': 'There is some error'}, 400


@admin_namespace.route('/<string:admin_id>')
class SingleUser(Resource):
    def get(self, admin_id):
        return jsonify(AdminAPI.get_admin_by_admin_id(admin_id))


@admin_namespace.route('/login')
class Authorize(Resource):
    @admin_namespace.doc(params={
        'username': {'in': 'formData', 'description': 'Username of Dot Admin', 'required': 'True'},
        'password': {'in': 'formData', 'description': 'Password of Dot Admin', 'required': 'True'}})
    def post(self):
        username = request.form['username']
        password = request.form['password']
        data = AdminAPI.authenticate_admin(username, password)
        if data:
            return {
                'status': 'success',
                'data': [AdminAPI.authenticate_admin(username, password)]
            }


@admin_namespace.route('/list-by-count')
class ListSimCount(Resource):
    @admin_namespace.doc(params={
        'count': {'in': 'formData', 'description': 'The no of count you want to query', 'required': 'True'}})
    def post(self):
        count = request.form['count']
        cluster_data = AdminAPI.gets_user_by_count(count)
        return {"msg": "successful",
                "data": [{'aadhaar': key, 'count': cluster_data[key]} for key in
                         cluster_data.keys()]} if cluster_data is not None or False else {'msg': 'No User'}


@admin_namespace.route('/list-by-lsa')
class ListSimlsa(Resource):
    @admin_namespace.doc(params={
        'lsa': {'in': 'formData', 'description': 'Local Service Area', 'required': 'True'}})
    def post(self):
        lsa = request.form['lsa']
        cluster_data = AdminAPI.list_users_by_lsa(lsa)
        return {"msg": "successful",
                "data": [{'aadhaar': key, 'count': cluster_data[key]} for key in
                         cluster_data.keys()]} if cluster_data is not None or False else {'msg': 'No User'}

src/models/dot/views.py
import requests
from flask import Blueprint, request, session, redirect, url_for, render_template, jsonify

from src.models.dot.dot import Admin
from src.models.dot.errors import AdminError

admin_blueprint = Blueprint('admin', __name__)

@admin_blueprint.route('/')
def home():
    if 'uid' not in session.keys() or session['uid']==None:
        return render_template('dot/home.html')
    else:
        return redirect(url_for('redirect_to_dash'))

@admin_blueprint.route('/dashboard/<user_id>')
def view_dashboard(user_id):
    admin = Admin.get_by_id(user_id)
    return render_template('dot/dashboard.html', admin = admin)


@admin_blueprint.route('/login', methods = ["GET", "POST"])
def login_user():
    if request.method == "POST":
        username = request.form['username']
        password = request.form['password']
        try:
            admin = Admin.is_login_valid(username, password)
            if admin:
                session['uid'] = admin._id
                return redirect(url_for(".redirect_to_dash"))
        except AdminError as e:
            return e.msg
    return render_template('dot/login.html')

@admin_blueprint.route('/to-dash/redirecting')
def redirect_to_dash():
    if session['uid']==None:
        return redirect(url_for('home'))
    else:
        return redirect(url_for('.view_dashboard', user_id = session['uid']))

@admin_blueprint.route('/list-by-lsa', methods = ['GET', 'POST'])
def list_by_lsa():
    if request.method == "POST":
        lsa = request.form["lsa"]

        data = Admin.list_users_by_lsa(lsa)
        return render_template('dot/lsa.html', data=data)
    return render_template('dot/lsa.html')


@admin_blueprint.route('/list-by-count', methods=["GET", "POST"])
def list_by_count():
    if request.method == "POST":
        count = request.form["count"]
        data = Admin.gets_user_by_count(count)
        return render_template('dot/sim_counts.html', data=data)
    return render_template('dot/sim_counts.html')

src/templates/dot/charts.html
{% extends 'base.html' %}
{% block title %}Charts{% endblock %}
{% block header %}
    <a class="navbar-brand" href="#">Department of Telecommunications Ministry of Communication</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar links -->
    <div class="collapse navbar-collapse text-white" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link text-white btn btn-danger" href="{{ url_for('logout') }}">Logout</a>
            </li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div class="mt-2 card bg-secondary text-center">
        <div class="d-flex flex-lg-row flex-sm-column flex-md-row flex-column p-2">
            <div class="col-sm-12 col-md-4 col-lg-4 flex-column">
                <img src="{{ url_for('static', filename = 'assets/images/ava.png') }}" height="150" width="150">
                <h3 class="text-white">{{ admin.username }}</h3>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-4 flex-column">

                <h3 class="text-white">Name</h3>
                <div class="text-white">{{ admin.name }}</div>
            </div>
        </div>
    </div>
    <div class="card mt-2 p-2">
        <div class="nav nav-pills">
            <div class="col-lg-6 col-md-6 col-sm-12 flex-column text-white">
                <a class="btn btn-success w-100 mt-2"><i class="fas fa-chart-pie"></i> Charts</a>
            </div>
        </div>
        <table id="myTable" class="table-bordered table-striped table-hover table-responsive display">
            <thead class="bg-dark text-white w-100">
            <tr>
                <th>Name</th>
                <th>explain</th>
                <th>content</th>
                <th>extension</th>
            </tr>
            </thead>
        </table>
    </div>
{% endblock %}


{% block javascript %}
    <script src="{{ url_for('static',filename='js/charts.js') }}"></script>
{% endblock %}

src/templates/dot/dashboard.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block header %}
    <a class="navbar-brand" href="#">Department of Telecommunications Ministry of Communication</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar links -->
    <div class="collapse navbar-collapse text-white" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link text-white btn btn-danger" href="{{ url_for('logout') }}">Logout</a>
            </li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div class="mt-2 card bg-secondary text-center">
        <div class="d-flex flex-lg-row flex-sm-column flex-md-row flex-column p-2">
            <div class="col-sm-12 col-md-4 col-lg-4 flex-column">
                <img src="{{ url_for('static', filename = 'assets/images/ava.png') }}" height="150" width="150">
                <h3 class="text-white">{{ admin.username }}</h3>
            </div>
            <div class="col-sm-12 col-md-4 col-lg-4 flex-column">

                <h3 class="text-white">Name</h3>
                <div class="text-white">{{ admin.name }}</div>
            </div>
        </div>
    </div>
    <div class="card mt-2 p-2">
        <h3>Menu</h3>
        <div class="nav nav-pills">

            <div class="col-lg-6 col-md-6 col-sm-12 flex-column text-white">
                <a class="btn btn-success w-100 mt-2" href = "{{ url_for('admin.list_by_lsa') }}" ><i
                        class="fas fa-building"></i> List User By LSA</a>
                <a class="btn btn-success w-100 mt-2" href = "{{ url_for('admin.list_by_count') }}"><i
                        class="fas fa-exclamation-triangle"></i> List User By Sim Counts</a>
            </div>
        </div>

    </div>
{% endblock %}


{% block javascript %}

{% endblock %}

src/templates/dot/home.html
{% extends 'base.html' %}

{% block header %}
    <a class="navbar-brand" href="#">Department of Telecommunications Ministry of Communication</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-white" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">

            {% if 'uid' not in session.keys() or session['uid'] == None %}
                <li class="nav-item">
                    <a class="nav-link text-white btn btn-success" href="{{ url_for('admin.login_user') }}">Login</a>
                </li>
            {% else %}

                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('.redirect_to_dash') }}">To Dash</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white btn btn-danger" href="{{ url_for('logout') }}">Logout</a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div class="jumbotron">
        <h1>About DOT</h1>
        <p class="text-justify">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum
            has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of
            type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the
            leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the
            release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing
            software like Aldus PageMaker including versions of Lorem Ipsum.It is a long established fact that a reader
            will be distracted by the readable content of a page when looking at its layout. The point of using Lorem
            Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here,
            content here', making it look like readable English. Many desktop publishing packages and web page editors
            now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites
            still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on
            purpose (injected humour and the like).

        </p>
    </div>
{% endblock %}

src/templates/dot/login.html
{% extends 'base.html' %}
{% block title %}DOT's Dashboard{% endblock %}

{% block header %}
        <a class="navbar-brand" href="#">Department of Telecommunications Ministry of Communication</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse text-white" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">

            {% if 'uid' not in session.keys() or session['uid'] == None %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for("admin.home") }}">Home</a>
                </li>
            {% else %}

                <li class="nav-item">
                    <a class="nav-link text-white" href="{{ url_for('.redirect_to_dash') }}">To Dash</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white btn btn-danger" href="{{ url_for('.logout') }}">Logout</a>
                </li>
            {% endif %}
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div class="center-wrapper">
        <div class="center-container">
            <div class="panel panel-default border border-light bg-light">

                <div class="panel-heading ">
                    <h3 class="panel-title ">DOT LOGIN</h3>
                </div>
                <div class="panel-body">
                    <form role="form" action="{{ url_for('admin.login_user')}}" method="POST">
                        <fieldset>
                            <div class="form-group">
                                <input class="form-control" placeholder="Username" name="username" type="text">
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" type="password">
                            </div>
                            <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/templates/dot/lsa.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block header %}
    <a class="navbar-brand" href="#">Department of Telecommunications Ministry of Communication</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar links -->
    <div class="collapse navbar-collapse text-white" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link text-white btn btn-danger" href="{{ url_for('logout') }}">Logout</a>
            </li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div class="card mt-2 p-2">
        <h3>Menu</h3>
        <div class="nav nav-pills">

            <div class="col-lg-6 col-md-6 col-sm-12 flex-column text-white">
                <a class="btn btn-success w-100 mt-2" href="{{ url_for('admin.list_by_lsa') }}"><i
                        class="fas fa-building"></i> List User By LSA</a>

            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 flex-column text-white">
                <a class="btn btn-success w-100 mt-2" href="{{ url_for('admin.list_by_count') }}"><i
                        class="fas fa-exclamation-triangle"></i> List User By Sim Counts</a>
            </div>
        </div>

    </div>
    <div class="card mt-2 p-2">

        <h2>List By LSA</h2>
        <form method="post" action="{{ url_for('admin.list_by_lsa') }}">
            <div class="form-group">
                <label for="lsa">LSA:</label>
                <input type="text" class="form-control" name="lsa" id="lsa">
            </div>
            <div class="form-inline">
                <button type="submit" class="btn btn-success">Search</button>
            </div>

        </form>
    </div>
    {% if data %}
        <div class="card mt-2 p-2">
            <table id="myTable" class="table-bordered table-striped table-hover table-responsive">
                <thead class="bg-dark text-white w-100">
                <tr>
                    <th>Aadhaar No</th>
                    <th>Sim Cards Issued</th>
                </tr>
                </thead>
                <tbody>
                {% for key in data.keys() %}

                    <tr>
                        <td>{{ key }}</td>
                        <td>{{ data[key] }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}

src/templates/dot/sim counts.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block header %}
    <a class="navbar-brand" href="#">Department of Telecommunications Ministry of Communication</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar links -->
    <div class="collapse navbar-collapse text-white" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">

                <li class="nav-item">
                    <a class="nav-link text-white btn btn-danger" href="{{ url_for('logout') }}">Logout</a>
                </li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div class = "card mt-2 p-2">
        <div class="nav nav-pills">
            <div class = "col-lg-6 col-md-6 col-sm-12 flex-column text-white">
            <a class = "btn btn-success w-100 mt-2"><i class="fas fa-exclamation-triangle"></i> List User By Sim Counts</a>
            </div>
        </div>

                  <form method="post" action = "{{ url_for('admin.ajax_by_count') }}">

           	  	      <div class="form-group">
           	  		      <label for="count">Count:</label>
           	  		      <input type="text" name="count" id = "count" >
           	  	      </div>

                  </form>
        <table id="myTable" class="table-bordered table-striped table-hover table-responsive display">
            <thead class="bg-dark text-white w-100">
            <tr>
                <th>Name</th>
                <th>content</th>
                <th>extension</th>
                <th>details</th>
            </tr>
            </thead>

        </table>
    </div>
{% endblock %}


{% block javascript %}
    <script src="{{ url_for('static',filename='js/lsa.js') }}"></script>

{% endblock %}

src/templates/dot/sim_counts.html
{% extends 'base.html' %}
{% block title %}Dashboard{% endblock %}
{% block header %}
    <a class="navbar-brand" href="#">Department of Telecommunications Ministry of Communication</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Navbar links -->
    <div class="collapse navbar-collapse text-white" id="collapsibleNavbar">
        <ul class="navbar-nav ml-auto">

            <li class="nav-item">
                <a class="nav-link text-white btn btn-danger" href="{{ url_for('logout') }}">Logout</a>
            </li>
        </ul>
    </div>
{% endblock %}
{% block body %}
    <div class="card mt-2 p-2">
        <h3>Menu</h3>
        <div class="nav nav-pills">

            <div class="col-lg-6 col-md-6 col-sm-12 flex-column text-white">
                <a class="btn btn-success w-100 mt-2" href="{{ url_for('admin.list_by_lsa') }}"><i
                        class="fas fa-building"></i> List User By LSA</a>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 flex-column text-white">
                <a class="btn btn-success w-100 mt-2" href="{{ url_for('admin.list_by_count') }}"><i
                        class="fas fa-exclamation-triangle"></i> List User By Sim Counts</a>
            </div>
        </div>

    </div>
    <div class="card mt-2 p-2">
        <h2>List By Sim Counts</h2>
        <form method="post" action="{{ url_for('admin.list_by_count') }}">
            <div class="form-group">
                <label for="count" class="label">Count</label>
                <input type="text" class="form-control" name="count" id="count">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Search</button>
            </div>

        </form>
    </div>
    {% if data %}
        <div class="card mt-2 p-2">
            <table id="myTable" class="table-striped table-hover">
                <thead class="bg-dark text-white">
                <tr>
                    <th>Aadhaar No</th>
                    <th>Sim Cards Issued</th>
                </tr>
                </thead>
                <tbody>
                {% for key in data.keys() %}

                    <tr>
                        <td>{{ key }}</td>
                        <td>{{ data[key] }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}